#!/usr/bin/env node
/**
 * Writes the local dev environment from the deployed stack's outputs.
 *
 * Local development runs against real AWS — the real Cognito pool and the real
 * DynamoDB table — so that auth and persistence behave exactly as they do in
 * production. This script is what stops those values from being copied by hand
 * and drifting.
 *
 * Produces two files, both git-ignored:
 *   .env.local          consumed by the local API server
 *   app/.env.local      consumed by Vite
 */
import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';

const STACK = process.env.STACK_NAME ?? 'PosterWalls';

function outputs() {
  const raw = execFileSync(
    'aws',
    [
      'cloudformation',
      'describe-stacks',
      '--stack-name',
      STACK,
      '--query',
      'Stacks[0].Outputs',
      '--output',
      'json',
    ],
    { encoding: 'utf8' },
  );
  return Object.fromEntries(
    JSON.parse(raw).map((o) => [o.OutputKey, o.OutputValue]),
  );
}

let o;
try {
  o = outputs();
} catch {
  console.error(
    'Could not read the stack outputs.\n' +
      'Most likely your AWS session has expired — run `aws login`, then retry.',
  );
  process.exit(1);
}

const API_PORT = process.env.PORT ?? '8787';

writeFileSync(
  '.env.local',
  [
    '# Generated by scripts/write-dev-env.mjs — do not edit, do not commit.',
    `TABLE_NAME=${o.TableName}`,
    `USER_POOL_ID=${o.UserPoolId}`,
    `USER_POOL_CLIENT_ID=${o.UserPoolClientId}`,
    `IMAGES_BUCKET=${o.ImagesBucketName}`,
    `PORT=${API_PORT}`,
    '',
  ].join('\n'),
);

writeFileSync(
  'app/.env.local',
  [
    '# Generated by scripts/write-dev-env.mjs — do not edit, do not commit.',
    `VITE_API_URL=http://localhost:${API_PORT}`,
    `VITE_COGNITO_DOMAIN=${o.CognitoDomain}`,
    `VITE_USER_POOL_CLIENT_ID=${o.UserPoolClientId}`,
    '# Images live on the deployed CloudFront distribution; there is no local',
    '# equivalent, so point at it directly rather than at the dev origin.',
    `VITE_IMAGE_BASE_URL=${o.WebUrl}`,
    '',
  ].join('\n'),
);

console.log('wrote .env.local and app/.env.local');
console.log(`  api  -> http://localhost:${API_PORT}`);
console.log(`  app  -> http://localhost:5173`);
console.log(`  data -> ${o.TableName} (real table)`);
